-- 코드를 작성해주세요
SELECT F.ID, N.FISH_NAME, F.LENGTH
FROM FISH_INFO F
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LEN
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) M
  ON F.FISH_TYPE = M.FISH_TYPE
 AND F.LENGTH = M.MAX_LEN
JOIN FISH_NAME_INFO N
  ON F.FISH_TYPE = N.FISH_TYPE
ORDER BY F.ID;